import { useState } from 'react';
import {
  AlertTriangle,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Download,
  Shield,
  XCircle,
  ArrowLeft,
  Loader2,
  ExternalLink,
} from 'lucide-react';

interface Vulnerability {
  severity: 'High' | 'Medium' | 'Low' | 'HIGH' | 'MEDIUM' | 'LOW';
  description: string;
  line?: number;
}

interface AuditReportProps {
  onBack: () => void;
  result?: {
    score: number;
    vulnerabilities: Vulnerability[];
    recommendations: string[];
  } | null;
}

export function AuditReport({ onBack, result }: AuditReportProps) {
  const [expandedId, setExpandedId] = useState<number | null>(null);

  if (!result) {
    return (
      <div className="min-h-screen bg-deep-space pt-40 px-4 flex flex-col items-center justify-center">
        <Loader2 className="h-10 w-10 text-neon-cyan animate-spin mb-4" />
        <p className="text-white/50 animate-pulse text-lg">Still processing neural audit results...</p>
      </div>
    );
  }

  const vulnerabilities = result.vulnerabilities || [];
  const securityScore = result.score || 0;

  const highCount = vulnerabilities.filter((v) => v.severity.toUpperCase() === 'HIGH').length;
  const mediumCount = vulnerabilities.filter((v) => v.severity.toUpperCase() === 'MEDIUM').length;
  const lowCount = vulnerabilities.filter((v) => v.severity.toUpperCase() === 'LOW').length;

  const getScoreColor = () => {
    if (securityScore >= 80) return 'text-matrix-green';
    if (securityScore >= 60) return 'text-warning-yellow';
    return 'text-danger-red';
  };

  const getScoreLabel = () => {
    if (securityScore >= 80) return 'SECURE';
    if (securityScore >= 60) return 'CAUTION';
    return 'CRITICAL';
  };

  const getSeverityStyles = (severity: string) => {
    switch (severity.toUpperCase()) {
      case 'HIGH':
        return {
          bg: 'bg-danger-red/10',
          border: 'border-danger-red/30',
          text: 'text-danger-red',
          icon: XCircle,
        };
      case 'MEDIUM':
        return {
          bg: 'bg-warning-yellow/10',
          border: 'border-warning-yellow/30',
          text: 'text-warning-yellow',
          icon: AlertTriangle,
        };
      case 'LOW':
        return {
          bg: 'bg-electric-blue/10',
          border: 'border-electric-blue/30',
          text: 'text-electric-blue',
          icon: CheckCircle,
        };
      default:
        return {
          bg: 'bg-white/5',
          border: 'border-white/10',
          text: 'text-white/60',
          icon: CheckCircle,
        };
    }
  };

  const circumference = 2 * Math.PI * 58;
  const dashOffset = circumference - (securityScore / 100) * circumference;

  return (
    <div className="min-h-screen bg-deep-space pt-20 px-4 pb-12">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8 animate-fade-in-up">
          <button
            onClick={onBack}
            className="glass rounded-lg p-2 hover:bg-white/10 transition-colors cursor-pointer"
          >
            <ArrowLeft className="h-5 w-5 text-white/60" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-white">Audit Report</h1>
            <p className="text-white/40 text-sm">Generated by AEGIS Neural Engine v2.1.0</p>
          </div>
        </div>

        {/* Score Card */}
        <div
          className="glass-strong rounded-2xl p-8 neon-border mb-8 animate-fade-in-up"
          style={{ animationDelay: '0.1s' }}
        >
          <div className="flex flex-col md:flex-row items-center gap-8">
            {/* Score Circle */}
            <div className="relative">
              <svg width="140" height="140" className="transform -rotate-90">
                <circle
                  cx="70"
                  cy="70"
                  r="58"
                  stroke="rgba(255,255,255,0.05)"
                  strokeWidth="8"
                  fill="none"
                />
                <circle
                  cx="70"
                  cy="70"
                  r="58"
                  stroke={securityScore >= 80 ? '#00ff88' : securityScore >= 60 ? '#ffd700' : '#ff3366'}
                  strokeWidth="8"
                  fill="none"
                  strokeDasharray={circumference}
                  strokeDashoffset={dashOffset}
                  strokeLinecap="round"
                  className="transition-all duration-1000"
                  style={{
                    filter: `drop-shadow(0 0 10px ${securityScore >= 80 ? '#00ff88' : securityScore >= 60 ? '#ffd700' : '#ff3366'
                      }40)`,
                  }}
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className={`text-3xl font-bold ${getScoreColor()}`}>{securityScore}</span>
                <span className="text-white/30 text-xs">/100</span>
              </div>
            </div>

            {/* Score Details */}
            <div className="flex-1 text-center md:text-left">
              <div className="flex items-center gap-2 justify-center md:justify-start mb-2">
                <Shield className={`h-6 w-6 ${getScoreColor()}`} />
                <span className={`text-lg font-bold ${getScoreColor()}`}>{getScoreLabel()}</span>
              </div>
              <p className="text-white/50 text-sm mb-4">
                AEGIS found {vulnerabilities.length} issues across your smart contract. Immediate
                attention required for {highCount} critical vulnerability.
              </p>
              <div className="flex gap-4 justify-center md:justify-start">
                <div className="glass rounded-lg px-4 py-2 text-center">
                  <p className="text-danger-red font-bold text-lg">{highCount}</p>
                  <p className="text-white/30 text-xs">High</p>
                </div>
                <div className="glass rounded-lg px-4 py-2 text-center">
                  <p className="text-warning-yellow font-bold text-lg">{mediumCount}</p>
                  <p className="text-white/30 text-xs">Medium</p>
                </div>
                <div className="glass rounded-lg px-4 py-2 text-center">
                  <p className="text-electric-blue font-bold text-lg">{lowCount}</p>
                  <p className="text-white/30 text-xs">Low</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* The Proof of Life: On-Chain Verification */}
        <div className="glass-strong rounded-2xl p-6 border border-matrix-green/20 mb-8 animate-fade-in-up flex flex-col md:flex-row items-center justify-between gap-4" style={{ animationDelay: '0.15s' }}>
          <div>
            <h3 className="text-white font-bold mb-1">On-Chain Proof of Life</h3>
            <p className="text-white/50 text-sm">
              Verify AEGIS's autonomous yield farming transaction ($4.50 staked to Aave V3).
            </p>
          </div>
          <a
            href="https://basescan.org/address/0xAEG1S00000000000000000000000000000000000"
            target="_blank"
            rel="noopener noreferrer"
            className="neon-button shrink-0 py-2 px-6 rounded-lg font-medium text-sm flex items-center gap-2 group cursor-pointer"
          >
            Verify on BaseScan
            <ExternalLink className="h-4 w-4 group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
          </a>
        </div>

        {/* Vulnerabilities */}
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-white/80 mb-4">Vulnerability Details</h2>
          {vulnerabilities.map((vuln, index) => {
            const styles = getSeverityStyles(vuln.severity);
            const IconComp = styles.icon;
            const isExpanded = expandedId === index;

            return (
              <div
                key={index}
                className={`glass rounded-xl border ${styles.border} overflow-hidden animate-fade-in-up`}
                style={{ animationDelay: `${0.2 + index * 0.1}s` }}
              >
                <button
                  onClick={() => setExpandedId(isExpanded ? null : index)}
                  className="w-full px-6 py-4 flex items-center gap-4 cursor-pointer hover:bg-white/[0.02] transition-colors"
                >
                  <IconComp className={`h-5 w-5 ${styles.text} shrink-0`} />
                  <div className={`${styles.bg} ${styles.text} px-2 py-0.5 rounded text-xs font-bold shrink-0`}>
                    {vuln.severity.toUpperCase()}
                  </div>
                  <span className="text-white/80 text-sm font-medium text-left flex-1">
                    {vuln.severity} level vulnerability detected on line {vuln.line || 'unknown'}
                  </span>
                  <span className="text-white/20 text-xs font-mono shrink-0">Line {vuln.line || 'N/A'}</span>
                  {isExpanded ? (
                    <ChevronUp className="h-4 w-4 text-white/30 shrink-0" />
                  ) : (
                    <ChevronDown className="h-4 w-4 text-white/30 shrink-0" />
                  )}
                </button>

                {isExpanded && (
                  <div className="px-6 pb-6 border-t border-white/5 pt-4 space-y-4 animate-fade-in-up" style={{ animationDuration: '0.3s' }}>
                    <div>
                      <h4 className="text-xs uppercase tracking-wider text-white/30 mb-2">
                        Description
                      </h4>
                      <p className="text-white/60 text-sm leading-relaxed">{vuln.description}</p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Global Recommendations from AI */}
        {result.recommendations && result.recommendations.length > 0 && (
          <div className="mt-8 space-y-4">
            <h2 className="text-lg font-semibold text-white/80 mb-4">AI Recommendations</h2>
            <div className="glass-strong rounded-xl p-6 border border-matrix-green/20 animate-fade-in-up" style={{ animationDelay: '0.6s' }}>
              <ul className="space-y-3">
                {result.recommendations.map((rec, idx) => (
                  <li key={idx} className="flex gap-3 text-sm">
                    <CheckCircle className="h-5 w-5 text-matrix-green shrink-0" />
                    <span className="text-white/80">{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Export Button */}
        <div className="mt-8 flex justify-center animate-fade-in-up" style={{ animationDelay: '0.8s' }}>
          <button className="neon-button rounded-xl py-3 px-8 text-neon-cyan font-semibold flex items-center gap-2 cursor-pointer">
            <Download className="h-5 w-5" />
            Download PDF Report
          </button>
        </div>
      </div>
    </div>
  );
}
